# Generated by Django 2.2 on 2021-07-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Managekey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='hoangdzsvipprovip chua nhap key', max_length=100)),
                ('owner', models.CharField(default='hoangdzsvip', max_length=200)),
                ('tool', models.CharField(default='Tool', max_length=200)),
                ('hsd', models.IntegerField(default=30)),
            ],
        ),
    ]
