# Generated by Django 2.2 on 2021-07-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_managekey_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managekey',
            name='date_create',
            field=models.CharField(default='2021-07-17', max_length=100),
        ),
    ]
