# Generated by Django 2.2 on 2021-07-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20210717_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='managekey',
            name='expiration_date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
