# Generated by Django 2.2 on 2021-07-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20210717_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managekey',
            name='hsd',
            field=models.CharField(default='30', max_length=50),
        ),
    ]
