# Generated by Django 2.2 on 2021-07-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20210717_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managekey',
            name='hsd',
            field=models.IntegerField(default=30),
        ),
    ]
